# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1383363cadc667c5aa5a9ebeb557b64a9cccdde2a43eb62802007276d51602fe9bf4d1a23d682ae978482da8ed389f75174e281475f20ee26de9df6c94fe1a47

test:
  secret_key_base: 952f6883830550e51501121e1515b53faf2f84f105bf8c0b900f4b7c500126363fc58d73eebc5283496f8122f643b94a72c58b0f78ce85f721cf617a40195e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
